if ( not PreformAVEnabler ) then
	PreformAVEnabler = {};
end

PreformAVEnabler.BG_NAME = {
	[1] = RANDOM_BATTLEGROUND,
	[2] = PREFORM_AV_ENABLER_AV,
	[3] = PREFORM_AV_ENABLER_WSG,
	[4] = PREFORM_AV_ENABLER_AB,
	[5] = PREFORM_AV_ENABLER_EYE,
	[6] = PREFORM_AV_ENABLER_STRAND,
	[7] = PREFORM_AV_ENABLER_ISLE,
	[8] = PREFORM_AV_ENABLER_TWIN,
	[9] = PREFORM_AV_ENABLER_GILNEAS,
	[10] = PREFORM_AV_ENABLER_SILVER,
	[11] = PREFORM_AV_ENABLER_TEMPLE,
};
PreformAVEnabler.NUM_BGS = #PreformAVEnabler.BG_NAME;
PreformAVEnabler.BG_ABR_NAME = {
	[1] = PREFORM_AV_ENABLER_RANDOM_ABR,
	[2] = PREFORM_AV_ENABLER_AV_ABR,
	[3] = PREFORM_AV_ENABLER_WSG_ABR,
	[4] = PREFORM_AV_ENABLER_AB_ABR,
	[5] = PREFORM_AV_ENABLER_EYE_ABR,
	[6] = PREFORM_AV_ENABLER_STRAND_ABR,
	[7] = PREFORM_AV_ENABLER_ISLE_ABR,
	[8] = PREFORM_AV_ENABLER_TWIN_ABR,
	[9] = PREFORM_AV_ENABLER_GILNEAS_ABR,
	[10] = PREFORM_AV_ENABLER_SILVER_ABR,
	[11] = PREFORM_AV_ENABLER_TEMPLE_ABR,
};
PreformAVEnabler.BG_ID = {
	[RANDOM_BATTLEGROUND] = 1,
	[PREFORM_AV_ENABLER_AV] = 2,
	[PREFORM_AV_ENABLER_WSG] = 3,
	[PREFORM_AV_ENABLER_AB] = 4,
	[PREFORM_AV_ENABLER_EYE] = 5,
	[PREFORM_AV_ENABLER_STRAND] = 6,
	[PREFORM_AV_ENABLER_ISLE] = 7,
	[PREFORM_AV_ENABLER_TWIN] = 8,
	[PREFORM_AV_ENABLER_GILNEAS] = 9,
	[PREFORM_AV_ENABLER_SILVER] = 10,
	[PREFORM_AV_ENABLER_TEMPLE] = 11,
};
